### ISSUE TITLE
`-k` option for API key not working, needs swapped

### ISSUE THREAD

**Issue by Obsecurus** [GreyNoise-Intelligence/pygreynoise#69] opened 2019-08-23 17:48 UTC
https://github.com/GreyNoise-Intelligence/pygreynoise/blob/e818d952f006723cd06dea26789d02b54c553038/src/greynoise/cli/subcommand.py#L39

Click documentation seems to suggest the long argument should always be first so `"--api-key", "-k"` instead.

**Comment by jcollado** [comment] 2019-08-27 09:32
@Obsecurus I see examples in the documentation that use the same ordering for short/long options. Could add more information about what is not working and how to reproduce it?

**Comment by jcollado** [comment] 2019-08-27 21:24
@Obsecurus Since it looks like now it cannot be reproduced, I'm going to close this issue. Feel free to reopen it if it happens again.

**Closed by jcollado** 2019-08-27 21:24 UTC
Labels: bug
